Repository whatwg/fetch, pull requests merged in 2018-05, with the labels that each got.

#626 Safelist Content-Length header
  fetch.bs
Labels: security/privacy

#734 Editorial: avoid normative keywords in domintro block
  fetch.bs
Labels: clarification

#594 Avoid using the CORS flag to reset request's origin in redirects
  fetch.bs
Labels: topic: cors

#738 Block AFP ports (427, 548)
  fetch.bs
Labels: addition/proposal, security/privacy, topic: port blocking
