Repository whatwg/fetch, pull requests merged in 2021-06, with the labels that each got.

#1248 Set final connection timing info after failure check
  fetch.bs
Labels: topic: timing

#1250 Block port 989, 990 (ftps-data and ftp)
  fetch.bs
Labels: topic: port blocking

#1245 Elaborate on obtaining a connection
  fetch.bs
Labels: clarification, topic: connections
