Repository whatwg/fetch, pull requests merged in 2021-02, with the labels that each got.

#1149 Remove location URL as field on responses
  fetch.bs
Labels: topic: redirects

#1166 Remove FTP support
  fetch.bs
Labels: removal/deprecation

#1144 Tee request body on ServiceWorker interception
  fetch.bs
Labels: topic: streams

#696 Align redirect fragment handling with HTTP
  fetch.bs
Labels: topic: redirects
