Repository whatwg/fetch, pull requests merged in 2022-05, with the labels that each got.

#1422 Perform TAO check for nested navigations
  fetch.bs
Labels: topic: timing

#1392 Add `Response.json` static method
  fetch.bs
Labels: addition/proposal, topic: api

#1441 Remove CORB
  fetch.bs
Labels: removal/deprecation, topic: corb
