Repository whatwg/fetch, pull requests merged in 2022-10, with the labels that each got.

#1343 Add abort reason to abort fetch
  fetch.bs
Labels: topic: api

#1468 Pass in response status to mark resource timing
  fetch.bs
Labels: do not merge yet

#1516 Editorial: WebSockets has its own standard now
  fetch.bs
Labels: meta
